# -*- coding: utf-8 -*-
"""Make your own Image AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVSpbPSLg8Pk5GVXOJGFdBIoCyeIM4VM

Input Function
"""

prompt = input("Enter your image prompt for the model: ") #User prompt

"""Image Stored"""

!pip install diffusers transformers accelerate

from diffusers import StableDiffusionPipeline
import torch

# Login with your Hugging Face token
from huggingface_hub import login
login("putYourTokenHere")

# Load the model
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float16,
    token="putYourTokenHere"
).to("cuda")  # Use GPU

# Generate an image
image = pipe(prompt).images[0]

# Display the image
from IPython.display import display
display(image)